machine:
  install:
    disk: /dev/sda 
    wipe: true
  network:
    hostname: muspelheimr
    nameservers:
      - 192.168.178.2
    interfaces:
    - interface: enp3s0
      addresses:
        - 192.168.178.14/23
      routes:
        - network: 0.0.0.0/0 # The route's network (destination).
          gateway: 192.168.178.1 # The route's gateway (if empty, creates link scope route).
          metric: 1024 # The optional metric for the route.
